### ISSUE TITLE
ToDo: Walle

### ISSUE THREAD

**Issue by alexanderWallrabenstein** [pirminrehm/neddit#23]
- [x] Notifications
- [x] Start page: Logging (Pirmin)
- [x] User: send token again
- [x] apply host type attributes list to: _formHost, allHosts, networkDetails
- [x] give each table column a fix width
- [x] Error handling (when server returns 500) --> Notification
- [ ] route, to get meta data of all networks
- [ ] route, to get meta data of a network by a host._id
- [ ] route, to get meta data of a network by its _id
- [x] edit config: User
- [x] List with all switches when editing a host
- [x] List with all nameservers when editing a network
- [x] resolve switches in host details
- [x] all hosts: buttons to scroll to a network (smooth scroll)
- [x] all hosts: hide tables with a search result
- [x] alias
- [x] menu: mark active tab as `active`
- [x] create a new menu tab to edit the config file
- [x] Exam mode: Unit management (switch all hosts between network 6 und 7)???
- [x] present ip0, ip1, ip2, netId as one ip address -> sorting
- [x] correct sorting of ip addresses
- [x] update constraints for network/host attributes in html form input elements
- [x] Buttons to trigger scripts (How many buttons?)
- [x] resolve nameservers in network details view
- [x] refactor controller to move a host (using a special route)
- [x] domains
- [x] modal to move a host to another network
- [x] restrict 'type' to client, server, printer, switch, etc. (data in config file)
- [x] unify the host move/edit/moveAndEdit function
- [x] make the network details panel 
- [x] security query before delete
- [x] use icons instead of large buttons
